# Generated by Django 3.2.8 on 2021-12-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsMedis',
            new_name='ProductsMedia',
        ),
    ]
